### ISSUE TITLE
Va, vis, deviens. Oui mais qui, quoi, comment ?

### ISSUE THREAD

**Issue by toughcrust** [toughcrust/toughcrust.github.io#15]
Faut-il se programmer ? faut-il des mantras / principes ? Faut-il une une discipline ou au contraire se relâcher ? Tout retenir, tout oublier, se contredire ou s'entêter ?
En contrepoint de l'"hygiène mentale" de l'issue #24 comment vivre cette expérience humaine à son paroxysme ?

**Comment by toughcrust** [comment]
**Joue le jeu. Menace le travail encore plus. Ne sois pas le personnage principal**. Cherche la confrontation. Mais n’aie pas d’intention. **Évite les arrière-pensées. Ne tais rien. Sois doux et fort.** Sois malin, interviens et méprise la victoire. N’observe pas, n’examine pas, mais reste prêt pour les signes, vigilant. Sois ébranlable. **Montre tes yeux, entraîne les autres dans ce qui est profond**, prends soin de l’espace et considère chacun dans son image. Ne décide qu’enthousiasmé. Échoue avec tranquillité. Surtout aie du temps et fait des détours. Laisse-toi distraire. Mets toi pour ainsi dire en congé. **Ne néglige la voix d’aucun arbre, d’aucune eau**. **Entre où tu as envie et accorde-toi le soleil**. Oublie ta famille, **donne des forces aux inconnus**, penche-toi sur les détails, pars où il n’y a personne, **fous-toi du drame du destin**, dédaigne le malheur, **apaise le conflit de ton rire. Mets-toi dans tes couleurs, sois dans ton droit, et que le bruit des feuilles deviennent doux**. Passe par les villages, je te suis.

``Peter Handke, Par les villages``

Dans l'esprit Deleuze / Damasio:
- faire plier la force du dehors qui nous fait plier
- tracer son sillage et emmener avec soi
- remuer / créer des tourbillons / enflammer, observer la vie prendre vie

**Comment by toughcrust** [comment]
I'd like to age in something like a badass transsexual grandpa eventually. You know, **no shit, low appetite,
big laugh, bigmouth, looking after of the offspring**. Having been satisfied an all levels, I now take pleasure in nurturing lifes, Life, what may live ...

**Comment by toughcrust** [comment]
One of the best feeling ever is to empower your weaknesses: Expose them to others with the strength of the fighter. **Be the puppet of your most intimate desires** and enjoy one of the most incredible thing ever:
- people will tell you're crazy and make you feel like a marginal or a romantic at best
- but that's actually when you'll truly connect with them

**In other words, live in the world you dream to live in. Be the explorer of your intimate unknown, the mercenary of your very fundamental excitement**

authentic == eccentric ?

**Comment by toughcrust** [comment]
Je suis pour les chefs ! Des chefs pour tout par tout. Tout le monde est chef pour des sujets différents, selon vélléité et affinités. **Prendre la responsabilité de ce qu'il "se passe"**, individuellement, et collectivement c'est encore mieux.
L'indignation, le combat c'est la vie qui se déploie.
Mais le kiff du "petit chef" est une prison dérisoire par rapport au **domptage d'un territoire sauvage ensemble, en famille, en meute, en tribu** !

**Comment by toughcrust** [comment]
Soyons voltés (La zone du dehors)

Vous vous ennuyez, les gens! L’actif en vous, le vif, a perdu ses adversaires, se morfond, n’a, pour ses conquêtes, plus d’espace, plus de front où aller tremper le métal de ses os ! Plus de quoi s’user, épuiser ses forces, hein? Ah si : dans les petits plaisirs : les capsules, les stimulations artificielles, la virtue, le jeu, les images… **Les gens ne sont pas morbides : ils veulent juste de l’intensité**

**Comment by toughcrust** [comment]
Jacques Salomé. Les relations avec les autres sont kiffantes quand notre relation à nous mêmes l'est déjà. La solitude est féconde. C'est l'écho chez l'autre de mes émotions qui créent des instants / des relations extatiques qui semblent échapper à l'utilitarisme. 
Toujours libérateur à relire:

- **Reconnaître l'expression de l'autre comme la sienne**. De même je ne laisse pas l'autre parler sur moi. Il ne s'agit pas d'être d'accord mais de mettre en commun ou en apposition.
- **Nous pouvons nous dire sur plusieurs niveaux: les faits / les sentiments / les idées / le retentissement émotionnel dans notre histoire / l'imaginaire**. Une communication féconde est satisfaisante sur ces 5 niveaux.
- **Reconnaître que la communication verbale est incomplète** (ce que l'on pense dire, comprendre...) et qu'il faut ajuster en permanence.
- **Savoir écouter sans chercher de réponse ou juger**: c'est un beau cadeau à offrir, donner et recevoir.
- **Pouvoir se dire et entendre sans enfermer ou se sentir enfermé: pouvoir être contradictoire**.
- **Dans une relation saine, demander / refuser / recevoir / donner sont réciproques et libres.** 

**Aimer à partir de notre plénitude et non de nos manques => mieux vaux être seul que mal accompagner.**

**Comment by toughcrust** [comment]
> Whatever you can do, or dream you can do, begin it. Boldness has genius, power, and magic in it. Begin it now.
`Goethe`

**Comment by toughcrust** [comment]
## Intuition de la joie comme attitude raisonnable
De la même manière que la croyance en tout me paraît raisonnable, j'ai l'intuition que la joie l'est tout autant.
D'expérience et de ce que je ressens, la joie est ouverture aux choses, accueil de ce qui est possible. L'absence de joie,
qui n'est pas nécessairement tristesse / dépression, constitue un filtre à ce qui est possible.
La question est donc: de quoi me coupe-je en m'emplissant de joie ? peut on explorer sa tristesse dans la "joie" ?
Ou faut il trouver un autre mot une autre résonance pour "joie" ?
En même temps la rage, "stand up for yourself", "indignez-vous" me paraît vital, au sens premier du terme. Est-ce qu'on peut
trouver un mode d'expression de la rage qui ait la puissance d'ouverture de la joie (métalleux du Hellfest ?)
Dévorer le monde, s'envivrer de joie extatique

**Comment by toughcrust** [comment]
**Randomness**
Harvest it, encourage, welcome and nurture randomness. Get the good pain out of it, the one that makes you grow and resist pain.

**Comment by toughcrust** [comment]
En vrac

je kiffe découvrir des plaisirs, des vérités insoupçonnées et pourtant tellement bons quand on les vit

**désintéressement passioné ! globalement les oxymores ça marche bien**. ça capture le besoin de mouvement. (FAIRE une blague avec oxy-moron)

Handle the drama you can and fuck the rest. Well actually things aren't that bad.

**Comment by toughcrust** [comment]
`for a life full of meaning, you don't follow your passions, your passions follow you` (contexte: faire ce qui nous attire, là où on réussit, la psssion suivra)

**Comment by toughcrust** [comment]
assouvir et sublimer

**Comment by toughcrust** [comment]
Chaque jour sauver de toute son énergie de la mort, de l'oubli, de la destruction, de l'indifférence les choses précieuses qui nout font vibrer. Vivre dans l'urgence du fragile, beau et précieux en devenir.

**Comment by toughcrust** [comment]
Ni hiérarchie ni territoire mais cartographie de terres envoûtantes. Plaisir à s'y mettre en danger et raconter les terres découvertes.
Marquer les pistes pour explorer la carte en indiquant ce qui résonne: intuition conviction fantasme espoir
Connecter les territoires, les lieux, créer des parcours, des pèlerinages. Se souvenir en repassant sur les chemins, couper à travers bois pour se perdre

**Comment by toughcrust** [comment]
L'une des plus belles sensations est de se sentir connecté avec quelqu'un
Une manière est de faire des voyages incroyables (ce qui en soit est cool mais par définition compliqué car c'est une compétition) pour trouver
au plus loin de sa vie quotidienne des éléments de surprise (ou à l'inverse justement un goût de familiarité au milieu de l'inconnu) l'évoquer et trouver l'écho de ce trésor chez la personne en face. Et créer instantanément ce genre de complicité qui se tisse habituellement dans la durée.
Ce n'et pas la même chose mais on peut faire plus simple: pour moi être sincère sur ce que je vis. Je trouve que dans mon coeur il y a de belles choses qui veulent s'exprimer, une rage de vivre puissante mais que ma vie est tout à fait naze faut de faire autre chose que de la rêver, faute d'énergie (de courage ?)

Je me rends compte qu'une des douleurs les plus sournoises à laquelle j'ai pas tellement de réponse, c'est ce besoin de se retrouver dans une soirée, un peu unique, hors du temps, une fille attirantes et de briller. Et je kiffe quand ça marche, mais j'en veux plus, en même temps je me lamente de ce que je n'ai pas vécu (ce même genre de rencontre ou ce que je n'ai pas fait avant) et au final je suis surtout triste. Mais je ressens que cette recherche de l'exception, du piquant, du risque, de la séduction a quelque chose d'extrêmement spirituel. Parce qu'on touche à une frontière, une singularité intense humainement, parce que ça nous touche, ça nous sublime et ça nous broie. Et quelque chose qui a ce pouvoir est forcément important.
je crois que ce qui est particulièrement marquant c'est le fait de se prendre en pleine face plien balle ce que c'est qu'être humain, les possibles qui sont ouverts, la fragilité de chaque instant, le pouvoir de la volonté, l'échaffaudage des souvenirs. Quand on passe des fois des semaines à agir comme un objet sans âme, je pense qu'il s'agit en fait d'une violence salutaire.

**Comment by toughcrust** [comment]
ETRE CEUX QUE J'AIME
----------------------

ne pas regretter envier les autres les faire vivre en soi
et vice versa die empty
Dévorer les autres des yeux, leurs passions et leurs joies (dans leur accomplissment, leur épanouissement), s'enflammer et les enflammer, s'embraser comme on s'embrasse ivre, entraîner la meute et se laisser entraîner
manger et être mangé, tuer et se laisser tuer. tuer pour rendre immortel.

**Comment by toughcrust** [comment]
écrivain passionné de la réalité et de ses possibles, j'éprouve de la joie à observer et ne pas **essayer** de changer le monde (mais vivre tout de suite maintenant une réalité différente), à ouvertement apprendre en permanence, être dans le mouvement, le léger (caracole)

**Comment by toughcrust** [comment]
**Ne jamais s'éloigner trop loin de ses plus belles émotions. Surtout ne pas en devenir étranger. Leur rendre visite. Rentre en collision.**
Je suis caracole dans un corps-esprit d'attachements
=> retrouver des extraits de Caracole et de Captp

**Comment by toughcrust** [comment]
Hier et Demain tuent le possible, cet animal de l'instant, cette bête aux yeux effarés prise en pleins phares, qui autrement se tapit dans les mirages de nos vies endormies.

**Comment by toughcrust** [comment]
**My inner peace needs a war**
Today I haven't had my share of love, fight, fear. The sun set a few hours ago but there's no drum to drive me crazy, dizzy and finally sloppy. I sure have my enemies, but they never show their faces. They eat me from the inside as I doubt my sanity. 

So here comes the night and here we are, lying in protest. 

I need a storm to burst so that I can find a shelter. 
I need cold, wild animals and spirits to fight so that I can light a fire. 
I need a tearing and hostile world so that I can long for true human binding.
Fuck me. litterally.

**Comment by toughcrust** [comment]
Les trucs à la con sur les gémeaux qui résonent en moi:
- Away from routine, to care and meaning

**Comment by toughcrust** [comment]
Hippie like a pro:
- be very serious about ecstasy and ideals

**Comment by toughcrust** [comment]
«N’aspire pas, ô mon âme, à la vie éternelle, mais épuise le champ du possible.» Pindare

**Comment by toughcrust** [comment]
Live & share ecstatic & evolutionary consciousness-shifting experiences

Ca me fait penser que ce genre de mission qui me parait finalement raisonable ne sera jamais en accord dans l'immédiat avec un boulot ou une vie amoureuse stable. Est-ce que je peut trouver plusieurs aspirations de ce type à différents niveaux de résonance sans me sentir soit enfermé soit "overwhelmed"

**Comment by toughcrust** [comment]
Enseignements du zodiaque même sans y croire:
- Nous sommes faits de polarités archétypales
- Ces polarités peuvent avoir des nuances complexes (timide en amour, brave en affaires)
- Rien de tout ça n'est évident

**Comment by toughcrust** [comment]
![image](https://user-images.githubusercontent.com/24764960/27288313-a5f3ba30-5506-11e7-9905-53ada94ca1ae.png)
![image](https://user-images.githubusercontent.com/24764960/27304154-7a8949e6-553d-11e7-872a-55051a85c008.png)
^--- Polich-Page house system and sidereal tropic (don't ask why).

Archetypes:
- Aries (Mars) The Initiator, Pioneer, Warrior
- Taurus (Venus) The Earth Spirit, Manifester, Builder
- Gemini (Mercury) The Communicator, Networker, Student
- Cancer (Moon) The Nurturer, Mother, Water Child
- Leo (Sun) The Leader, Golden Child, Performer
- Virgo (Mercury) The Server, Healer, Worker, Humble One
- Libra (Venus) The Harmoniser, Diplomat, Relator
- Scorpio (Pluto, Mars) The Transformer, Seeker, Psychologist
- Sagittarius (Jupiter) The Philosopher, Explorer, Wise Teacher
- Capricorn (Saturn) The Purposeful One, Father, Time Lord
- Aquarius (Uranus, Saturn) The Humanitarian, Reformer, Global One
- Pisces (Neptune, Jupiter) The Compassionate One, Mystic, Dreamer

Planets in signs and houses
---------------------------

a - Sun in Taurus and 11th House
b - Moon in Aquarius and 7th House
c - Retrograde Mercury in Gemini and 11th House. This is a major aspect of their psyche!
d - Retrograde Venus in Gemini and 11th House
e - Mars in Aquarius and 8th House
f - Jupiter in Aries and 10th House
g - Retrograde Saturn in Sagittarius and 5th House
h - Retrograde Uranus in Sagittarius and 5th House
i - Retrograde Neptune in Sagittarius and 5th House: It is easy for them to express this part of themself.
j - Retrograde Pluto in Libra and 4th House
k - Retrograde North Node in Aquarius and 8th House. This is a major aspect of their psyche!
l - South node in Leo and 2nd house
m - Chiron in Gemini and 11th House


Interpretations
---------------------------

a - My basic drive revolves around practicality, manifesting, enjoying. I'm mainly focused on friends, society and their aspirations.

b - My emotional longing is one of universal understanding, tied to a desire for societal changes. It is acute in long term partnerships, love or affair.
=> I dream to love freely in a group. At the sam time unfaithful to one, loyal to all

c - I am curious in an engaged way, liking to gather, analyse and share information. societal questions are my favorites. 

d - Exciting ideas is fundamental in my romantic / artistic inclinations. Especially when talking about friends, society aspirations. (banksy)

e - I take actions / fight as a humanitarian revolutioner (strong idea we've all got common ground). Mostly regarding harsh life issues, circulations (money, death, sex).

f - I hope to further develop as a pioneer, a leader especially in the area of achievements, social status and power

In my needs for 
g - filling a sense of duty / security
h - pursuing of higher humanity goals
i - spiritual awakening, imagination channelling
I tend to develop an open and wise approach
With fun, creativity as a main focus

j - My catharsis (obsession) is about balancing my inner life, easing communication with myself.

k - My growth potential is to pursue a humanitarian impulse to tackle harsh life issues

l - My innate comfort lies in the defense of my belongings

m - The part of my life that needs healing so that I can heal others too concerns friends and takes place at the mind level
=> I need to be able to reach out to others

Lots of retrograde planets: naturally against the flow and like it.


Walter pullen simple chart delineation
---------------------------

```
  Planet:    Position      Aspects    Total Rank  Percent
     Sun:   45.0 ( 4) +   3.0 ( 9) =   48.0 ( 6) /   7.8%
    Moon:   55.0 ( 2) +  13.5 ( 8) =   68.5 ( 4) /  11.2%
 Mercury:   43.5 ( 6) +  21.6 ( 5) =   65.1 ( 5) /  10.6%
   Venus:   52.5 ( 3) +  22.5 ( 4) =   75.0 ( 3) /  12.2%
    Mars:   45.0 ( 5) +  32.1 ( 1) =   77.1 ( 2) /  12.6%
 Jupiter:   40.0 ( 7) +   0.0 (10) =   40.0 ( 9) /   6.5%
  Saturn:   20.0 (10) +  24.4 ( 2) =   44.4 ( 8) /   7.2%
  Uranus:   59.5 ( 1) +  23.2 ( 3) =   82.7 ( 1) /  13.5%
 Neptune:   20.0 (11) +  14.2 ( 7) =   34.2 (10) /   5.6%
   Pluto:   28.5 ( 8) +  16.7 ( 6) =   45.2 ( 7) /   7.4%
  Chiron:    7.0 (12) +   0.0 (11) =    7.0 (12) /   1.1%
    Node:   27.0 ( 9) +   0.0 (12) =   27.0 (11) /   4.4%
   Total:  443.0      + 171.0      =  614.0      / 100.0%

       Sign:  Power Rank  Percent
      Aries:   36.9 ( 8) /   6.0%
     Taurus:   39.9 ( 7) /   6.5%
     Gemini:   76.8 ( 2) /  12.5%
     Cancer:   27.5 ( 9) /   4.5%
        Leo:   56.4 ( 4) /   9.2%
      Virgo:   13.1 (12) /   2.1%
      Libra:   52.2 ( 5) /   8.5%
    Scorpio:   48.7 ( 6) /   7.9%
Sagittarius:   75.8 ( 3) /  12.4%
  Capricorn:   20.0 (10) /   3.3%
   Aquarius:  147.4 ( 1) /  24.0%
     Pisces:   19.2 (11) /   3.1%
      Total:  614.0      / 100.0%
```

houses ratios:
--------------

```
House  Occurences  Ratio

2nd    1           7.7%
4th    1           7.7%
5th    3           23%
7th    1           7.7% 
8th    2           15.4%
10th   1           7.7%
11th   4           30.8%  
```
Opposition Gemini - Sagittarius
When opposing signs are in balance, certain traits emerge that transcend either sign individually and allow for the heuightened functioning of both
Gemini energy: gather raw data, ask a myriad of questions, gain clarity as to the basic signifance of how things as a separate entity.
=> left brain
Sagittarius energy: Synthetizer, know it all, seeks comprehensive view that speaks to the order of the universe (disparate parts => big picture)
=> right brain

synthesis: a honest appreciation of logic while making room for intuitive insights which come by way of inspiration

my houses interpretation
```
              1st -> 6th         7th -> 12th
freedom       independence       inter-dependence
property      get                take and share
thinking      isolate / observe  synthetize
pride         inner              outer
aspirations   personal           group
service       self and others    oneness        
```

**Comment by toughcrust** [comment]
Sun   basic drive
Moon   longing
Mercury   curiosity
Venus   affection
Mars   aggression
Jupiter   luck
Saturn   duty
Uranus   contemplation
Neptune   fantasy
Pluto   catharsis
Ascendant, AC   attitude
Medium Coeli, MC   self-image

**Comment by cedricco** [comment]
Il faut laisser s'exprimer le créateur. Celui qui imagine ou espère des choses farfelues  (ne se nourrir que d'air et de lumière ). Mais le respect doit aller dans les 2 sens: que cette liberté respecte le sceptique, le pratique, etc..

**Comment by toughcrust** [comment]
Ancres, aimants, polarités que me donne le "miroir" de mes astres à la naissance:
- Les besoins de connection avec les autres et la recherche de sens sont liés à mes insécurités, s'exprime dans le philosophe, le voyageur, le sage et se cherchent dans la romance, le fun la création => chorale qui chante du mackelmore en pleine braderie aussi bien que des chants shamaniques en pleine forêt.
- je cherche basiquement à éprouver du plaisir, j'aime, communique et pense essentiellement dans le registre des idées dans la communauté, les amis, les aspirations humaines (Banksy). Mais c'est paradoxalement là où je dois guérir ma communication, arriver à aller vers les autres. prendre des responsabilités ne me dérange pas (surtout si c'est un sujet qui me tient à coeur et que personne ne prend les devant) mais ça ne me gêne absolument de ne pas être sur le devant de la scène du moment que je sens que je contribue à la hauteur de mon potentiel
- Briller professionellement me fait m'épanouir
- Mes combats, ma mission, mes émotions s'incarnent dans l'humanitaire, celui qui se reconnaît dans chacun et se focalisent sur les questions difficiles d'échange et de partage: l'argent, le sexe, l'environnement. => le bio, le revenu minimum, la protection des plus faibles (un toît, à manger) et de l'environnement
- Mon poids est l'anxiété, la difficulté à lâcher prise, la peur de manquer, de ne pas avoir, **de la perte**
- My catharsis (obsession) is about balancing my inner life, easing communication with myself.

mélange: importance de la pop culture, de l'insclusivité, du journalisme d'investigation fun (john oliver), d'un équilibre entre pensée logique et intuitive.

Je n'ai pris que ce qui m'intéressait dans l'horoscope: ce qui résonne en moi. peut m'importe la scientificité de la démarche / la "vérité", ce qui m'intéresse c'est de faire émerger le plaisir que mon corps / esprit / whatever est désireux de faire émerger / vivre.

**Comment by toughcrust** [comment]
I WANT IT ALL, même la sérénité qui vient quand on s'est convaincus qu'on ne peut pas tout avoir, même le regard apaisé du contemplateur qui n'a pas peur de la perte parce qu'il n'a rien à perdre. La grande gueule, le danger, la la profonde sincérité, l'absence de masque.

Somehow related: what's wrong with willing to be god ? I am wind, earth, emptyness, symbiosis of a multitude and I acknowledge it. Still I dream to be one, to be god. What's wrong with that ?

**Comment by toughcrust** [comment]
La beauté de la vie est dans le précieux, le fragile, l'insoupçonné, l'éphémère, le subtile. C'est con de se planter à rêver à quelque chose qui en fait est naze, donc paradoxalement ça vaut le coup d'explorer assez "brutalement" la vie pour savoir ce qui nous fait rêver exactement ou pas. Juste, ne pas détruire (exploration non invasive).
