### ISSUE TITLE
Pain & cherries

### ISSUE THREAD

**Issue by toughcrust** [toughcrust/toughcrust.github.io#16]
> Pleasure is the only thing worth having a theory about
`Oscar Wilde`

Absolument tout ce qu'on peut rechercher dans la vie tourne autour de la recherche du plaisir
Plaisir et douleur sont les uniques choses qui ont une consistance. **Derrière une morale rigoriste se cache une recherche de plaisir voilée, qui ne dit pas son nom**.

> La frustation existentielle n'est pas pathologique
`Frankl`

> He who has a why to live can bear almost any how
`Nietzsche`

**C'est pas honteux ni même fondamentalement anormal de souffrir. Ce serait même plutôt l'inverse.**

Je crois qu'on a de plaisir qu'en réponse à une souffrance vécue ou imaginée.
Transformer les peurs et souffrances floues, imprécises en quelque chose de consistant. Pour les atténuer mais surtout pour faire émerger la joie dual => développer sa capacité à la joie.
Cas extrême de la dépression: être à fleur de peau, hyper-conscient du fait d'être en vie et de ce que l'on imagine manquer

**Profiter de sa tristesse, la laisser nous envahir comme on se laisse submerger par le plaisir ? Ne pas en avoir honte / l'ignorer mais l'écouter, la chérir presque comme signe d'humanité et de propension à la joie.**

**Comment by toughcrust** [comment]
Idée à developper sur la dépression. Il y a un paradoxe entre:
- Le fait de se sentir insensible au plaisir, "numb"
- Être à fleur de peau, hyper-conscient du fait d'être en vie et de ce que cette vie pourrait être

**Comment by toughcrust** [comment]
L'amour se puise et s'éteint dans la (belle) chair, tout en nourrissant des instincts de nature différentes et quelque part plus désirables (la compassion).
De manière un peu similaire nous sommes schizophrènes vis-à-vis des animaux... On peut facilement les anthropomorphiser et les tuer en masse après les avoir fait souffrir toute leur vie.
Les deux sont extrêmement perturbants et source de conflits. WHAT TO DO ? 

Un peu en décalage mais lié: est-ce que créer se situe sur une brèche où l'on déchire et recolle en permanence une unité fuyante ?
Une activité créative permet de dé-fragmenter (comme on empile des cartons pour prendre de la hauteur). Paradoxalement, c'est la fragmentation, qui en imposant des contraintes, permet à la créativité de s'exprimer. Autrement dit la richesse de l'expérience humaine naît dans le détachement vis à vis de la vie mais prend paradoxalement sa source et réside dans des vécus contradictoires.

Manger des animaux, manger ceux qu'on aime: forcément "mal" au delà du dégoût que ça me provoque (mais que j'ai vis à vis de mon propre corps) ?
par contre je suis certain que l'élevage industriel ou toute souffrance est une horreur. La mort, la souffrance ne doivent pas faire partie de la vie des animaux.
Quand je vois une vâche je n'ai pas l'impression qu'elle a le même attachement à la vie que moi. Je suis convaincu par contre que son expérience de conscience est similaire (mais qui suis-je pour en juger ?)

**Comment by toughcrust** [comment]
**Profiter de sa tristesse, la laisser nous envahir comme on se laisse submergé par le plaisir tout en se distanciant ? Ne pas en avoir honte, l'ignorer mais l'écouter, la chérir presque comme signe d'humanité et de propension à la joie puisque capable de tristesse ?** => **L'intensité de ta joie sera à la mesure de la tristesse que tu sais accueillir, chérir presque**

**Comment by toughcrust** [comment]
Très important: une nuance à apporter à cette discussion sur plaisir / douleur: l'inconfort.
L'incofort du voyage, de l'effort sportif, du défi sont des "douleurs" qui rendent plus vivants. Donc:
- combattre la douleur
- étendre sa zone de confort
- accueillir le plaisir

**Comment by cedricco** [comment]
Le plus gros problème qui est un peu moteur de toutes ces reflexions c'est qu'une fois qu'on a appris que le plaisir c'est tout ce qui compte, qu'on  peut très facilement s'auto illusionner / être influencé  sur le plaisir qu'on recherche, il reste que des fois la sensation de plaisir ne vient pas quand on pense qu'elle devrait. Que faire dans ces cas là ?

**Comment by cedricco** [comment]
Mark manson: le plaisir d'en avoir rien à faire
