### ISSUE TITLE
Brain food wishlist !

### ISSUE THREAD

**Issue by toughcrust** [toughcrust/toughcrust.github.io#20]
https://usbeketrica.com/article/pierre-ducrozet-dans-la-tete-des-nouveaux-maitres-du-monde

http://pwn.lu/sf-fantasy-books.jpg

https://www.amazon.com/Pencil-Me-Business-Drawing-People/dp/0996006036/ref=as_li_ss_tl?ie=UTF8&qid=1506525482&sr=8-1&keywords=Pencil+Me+In&linkCode=sl1&tag=eleganthack&linkId=ba008220c67821b84f823c09c3d48e2a

Lecture
----------

SF tonio:
- The Dispossessed / The Left Hand of Darkness d'ursula le guin
- The giver / Gathering Blue de Lois Lowry
- conseillés à aimée:
La passe miroir (Christelle Dabos) tome 1-> FR
Uprooted (Naomi Novik) -> EN
Redshirts (John Scalzi) -> EN
The Goblin Emperor (Katherine Addison) -> EN
https://www.babelio.com/livres/Sanderson-Elantris--Integrale/258515

regarder les prix Hugo/Nebula/locus

Spiritualité:
- https://fr.wikipedia.org/wiki/La_Philosophie_de_la_libert%C3%A9
- Jung and astrology
- The Tibetan Book of Living and Dying, by Sogyal Rinpoch

Self-help:
- radical honesty http://www.goodreads.com/book/show/551511.Radical_Honesty_?from_search=true

Histoire:
- A Thousand Years of Nonlinear History

Paleo-ish:
- Man & food, Matthieu Paley

Société / politique:
- https://www.amazon.fr/Leisure-Basis-Culture-Josef-Pieper/dp/0865972109
- Tractatus theologico-politicus de Spinoza
- https://www.amazon.com/Why-Nations-Fail-Origins-Prosperity/dp/0307719227
- https://www.amazon.fr/%C3%89copunk-punks-animale-%C3%A9cologie-radicale/dp/2369350369
- https://eowilsonfoundation.org/half-earth-our-planet-s-fight-for-life/

Design:
- https://www.amazon.com/Universal-Principles-Design-Revised-Updated/dp/1592535879/
- https://design.blog/ (design et inclusion)
- `Thought as a Technology` http://cognitivemedium.com/tat/index.html
- Trouver un résumé de "Nudge: Improving Decisions about Health, Wealth, and Happiness"

Romans:
- Faust de Goethe
- Silo, les suites
- American gods

Chic flicks
-------------
- Opération dragon de bruce lee
- life aquatic wes andersen
- les ailes du désir, wim wender
- Merci patron
- visages, villages
- le caire confidentiel
- soleil vert
- https://www.youtube.com/watch?v=L8QZEVTeHFY => le nom des gens
- https://www.youtube.com/watch?v=TnzD-XRXiHk => cleo de 5 à 7

Usbek & Rica
------------------

- la série https://usbeketrica.com/article/design-fiction-pourquoi-etudier-des-collections-d-imaginaires ! l'épisode 8 sur le story telling était super chouette. vient de https://www.amazon.fr/Jouer-avec-futurs-Utilisez-entreprise/dp/274406646X

Thèmes intéressants
---------------------------

- The blue economy: http://www.theblueeconomy.org/
- réflexes archaïques

Séries
--------
- https://www.wired.com/story/the-handmaids-tale-emmys?mbid=nl_091617_daily&CNDID=%%CUST_ID%%

Auteurs
----------

- Walt whitman
- Oscar Wilde
- Goethe
- le mec allemand du bio dynamique et des écoles cools

**Comment by toughcrust** [comment]
Stuff you saw you thumb up
-------------------------------------

- It follows
- Belle du seigneur
- La horde du contrevent
- La zone du dehors
- Belgica
- Fight club
- Shaun of the dead
- SIlo
- Inception
- Spin
- Perfect senses
- Arrival
- Comment c'est loin
- La loi de la jungle
- Lego the movie
- Le nom des gens
- ZombieLand
- Superbad
- Paleo Manifesto

**Painful (or boring) but structuring**
- Perfect health diet
- Search for meaning Frankl
- Le chateau de Kafka
- The moral animal
- Si je m'écoutais je m'entendrais
- Freedom from the known Krishnamurti

**Comment by toughcrust** [comment]
Humoristes:
- Vincent dedienne
- Chris esquerre
- John oliver
- Action discrète
- Petit journal
- Amy schumer

**Comment by toughcrust** [comment]
http://thoughtcatalog.com/daniel-coffeen/2014/11/the-fascist-inside-us/
```
In his exquisite introduction to Anti-Oedipus, Foucault suggests the book is an “Introduction to the Non-Fascist Life.” This art of living counter to all forms of fascism, he writes, whether already present or impending, carries with it a certain number of essential principles. He goes on to list these principles:

- Free yourself from totalizing paranoia
- Act and think multiplicity, proliferation, juxtaposition (as distinct from pyramidal hierarchy)
- Disavow all forms of the Negative
- Remember that you don’t need to be sad to be militant
- Don’t become enamored of power
```

**Comment by cedricco** [comment]
the Structure of Scientific Revolutions ?
The subtile art of not giving a fuck.
https://markmanson.net/6-books

**Comment by cedricco** [comment]
the Structure of Scientific Revolutions ?
The subtile art of not giving a fuck.
https://markmanson.net/6-books

**Comment by toughcrust** [comment]
chorale pop: https://www.lumiiq.com/uniisson/?gclid=CjwKEAjws-LKBRDCk9v6_cnBgjISJAADkzXeT4hEOIolXkbKxVm_xcdrTO621DdYaeFRldObz5btcBoCnJPw_wcB#infospratiques
