### ISSUE TITLE
Hygiène quotidienne

### ISSUE THREAD

**Issue by toughcrust** [toughcrust/toughcrust.github.io#24]
**être un bon parent pour soi** (Jacques Salomé)
- Reconnaître l'expression de l'autre comme la sienne. De même je ne laisse pas l'autre parler sur moi. Il ne s'agit pas d'être d'accord mais de mettre en commun ou en apposition.
- Nous pouvons nous dire sur plusieurs niveaux: les faits / les sentiments / les idées / le retentissement émotionnel dans notre histoire / l'imaginaire. Une communication féconde est satisfaisante sur ces 5 niveaux.
- Reconnaître que la communication verbale est incomplète (ce que l'on pense dire, comprendre...) et qu'il faut ajuster en permanence.
- Savoir écouter sans chercher de réponse ou juger: c'est un beau cadeau à offrir, donner et recevoir.
- Pouvoir se dire et entendre sans enfermer ou se sentir enfermé: pouvoir être contradictoire.
- Dans une relation saine, demander / refuser / recevoir / donner sont réciproques et libres. 

Mieux vaux être seul que mal accompagné/er: aimer à partir de notre plénitude et non de nos manques.

**Idées en cas de coup de mou**:
- Classiques: manger "sain" / peloter un sein / reach out
- Freestyle tout pourri façon orelsan
- Sunday checkout pour mettre de côté la merdouille
- S'enraciner avec un peu d'humour (meurice, quotidien, dedienne) ou de l'info cool (vice, telerama)
- Fire and welcome contradictions / Fight loose
- `Zen of pure physical effort` / `Violence mediaded meditation`: séance muscu intense / haka intense, courir à la cool pieds nus
- "to protect and entertain" pour hijack le cerveau

**Fuck la routine**:
- Meilleure chose au monde: s'offrir ou offrir des instants d'authenticité inédite: souvenir communs, voyages séparés, détail fun du quotidien, série cool, boss à la con, blessure personnelle
- Il faut faire des trucs cons / fous régulièrement pour nourrir cette authenticité

**Techniques de méditation**:
- "méditation pleine conscience": regarder ce qui "passe" à la conscience et l'examiner de façon méticuleuse mais détachée. .
- Faire circuler / débloquer les énergies se revitaliser. L'énergie croupie pourrit les gens => cycles d'ordres / désordre - inspiration / expiration.
- So, what smells like bullshitty crap in there ? On the contrary what resonnates ?
- Ressentir physiquement que l'on rayonne de bien-être

Pour les 2 premiers points, ce conseil:
Focus on your breath. You can think “in” as your breath goes in and “out” as your breath goes out if it helps you focus. Label Lefty [brain]. When Lefty brings the circus to town in your head, use a word to label his chatter and dampen it

**Comment by toughcrust** [comment]
Antidote par problème:
- démotivation, fatigue: sport intensif avec moults cris
- tristesse: se faire une impro hip hop
- nostalgie: ptite vidéo de stand-up

**Comment by toughcrust** [comment]
## Sunday checkout / mindful meditation
Se lever le dimanche matin et faire son programme du boulot pour le lendemain. Très cool. Ca me fait penser à ce qu'est pour
moi la "méditation pleine conscience": regarder ce qui "passe" à la conscience et l'examiner de façon méticuleuse mais détachée.
Laisser ce qui est complexe / flou parce que laissé dans le champ périphérique de la vue se décanter à l'observation.

**Comment by toughcrust** [comment]
ptits rdv quotidiens (meurice / quotidien / ...)
s'abonner à télérama ou inrocks

**Comment by toughcrust** [comment]
`Violence meditaded meditation` => atteindre ce point d'effort physique qui est un mélange de douleur et d'exaltation intense, où toute peur se noit dans une belle rage.

"the zen of pure physical effort"

**Comment by toughcrust** [comment]
**Hygiène mental:**
- **Jouir**
- **Contradictions, fire up ! I'm ready for you**
- **So, what smells like bullshitty crap in there ? On the contrary what resonnates ?**
- **Wrapping it up, let's make an actual shit (quick but leave a mark). Retour à la jouissance**

**Comment by toughcrust** [comment]
Analyse du corps: la pensée à des répercussions sur le corps. Est-ce que je me sens bien détendu dans les jambes, le ventre, le coeur, etc ... ? Idéalement "rayonner" également de ce bien être. Quoi qu'il en soit se rebiffer quand la zone de confort se (idem quand qqun veut nous forcer à penser qque chose auquel on adhère pas, on sent son espace vital se réduire)

**Comment by toughcrust** [comment]
courir doucement pieds nus et haka free fight ultra violent

**Comment by toughcrust** [comment]
**SELF VALIDATION**

**Comment by toughcrust** [comment]
ecstasy meditation:
- penser à comment jouir là tout de suite pendant quelques minutes
- Additionner les idées positives
- Contrer les émotions négatives par des solutions, mêmes totalement connes
lemme:
nous sommes faits de polarités qui souvent nous font ressembler à des zombies. Il faut s'autoriser à n'aller que dans le sens de la jouissance quelques instants pour enfin explorer ces idéaux qu'on entrevoit seulement

un peu la même idée qu'un brainstorming bien organisée: sortir d'un fonctionnement nominal, naturel (mais pas forcément si dingue que ça) pour réussir à s'excentrer un peu de ses pensées routinières, usuelles

**Comment by toughcrust** [comment]
Pour les choses qui reviennent plus d'une fois: se poser pour y réfléchir vraiment, laisser le problème prendre toute son ampleur sans se réfréner.
De la même manière ces traces de joies possibles et fugaces en nous qu'on ignore (parce que floue ou qu'on sait impossible) leur laisser de la place. "Be a pro" about it. En faire des chevaux de bataille, des devoirs / droits.

**Comment by toughcrust** [comment]
On the imoprtance of saying thank you and **fuck you**:
- be grateful for what has been given to you
- let you free to use it as I you wish, it's not a package

**Comment by toughcrust** [comment]
mettre truc sur les archztypes partagés par tous, comment ils sont activés ou non, pourquoi il faut s'y intéresser, pourquoi il faut s'en détacher
+ rage & joie & tristesse (transmuter en émotions basique c'est sain)

**Comment by cedricco** [comment]
Ne pas manger quand on est triste fatigué ou en colère ?

**Comment by cedricco** [comment]
Ne pas manger quand on est triste fatigué ou en colère ?
